In [ ]:
from google.colab import files
uploaded = files.upload()

Saving MFG10YearTerminationData.csv to MFG10YearTerminationData.csv

In [ ]:
import pandas as pd
x = pd.read_csv('MFG10YearTerminationData.csv')

In [ ]:
x.isnull().sum().sort_values(ascending=False)

EmployeeID             0
recorddate_key         0
birthdate_key          0
orighiredate_key       0
terminationdate_key    0
age                    0
length_of_service      0
city_name              0
department_name        0
job_title              0
store_name             0
gender_short           0
gender_full            0
termreason_desc        0
termtype_desc          0
STATUS_YEAR            0
STATUS                 0
BUSINESS_UNIT          0
dtype: int64

In [ ]:
x.nunique().sort_values()

gender_full               2
gender_short              2
BUSINESS_UNIT             2
STATUS                    2
termtype_desc             3
termreason_desc           4
STATUS_YEAR              10
department_name          21
length_of_service        27
city_name                40
store_name               46
age                      47
job_title                47
recorddate_key          130
terminationdate_key    1055
orighiredate_key       4415
birthdate_key          5342
EmployeeID             6284
dtype: int64

In [ ]:
x[['STATUS','termreason_desc','termtype_desc']].head(20)

    STATUS termreason_desc   termtype_desc
0   ACTIVE  Not Applicable  Not Applicable
1   ACTIVE  Not Applicable  Not Applicable
2   ACTIVE  Not Applicable  Not Applicable
3   ACTIVE  Not Applicable  Not Applicable
4   ACTIVE  Not Applicable  Not Applicable
5   ACTIVE  Not Applicable  Not Applicable
6   ACTIVE  Not Applicable  Not Applicable
7   ACTIVE  Not Applicable  Not Applicable
8   ACTIVE  Not Applicable  Not Applicable
9   ACTIVE  Not Applicable  Not Applicable
10  ACTIVE  Not Applicable  Not Applicable
11  ACTIVE  Not Applicable  Not Applicable
12  ACTIVE  Not Applicable  Not Applicable
13  ACTIVE  Not Applicable  Not Applicable
14  ACTIVE  Not Applicable  Not Applicable
15  ACTIVE  Not Applicable  Not Applicable
16  ACTIVE  Not Applicable  Not Applicable
17  ACTIVE  Not Applicable  Not Applicable
18  ACTIVE  Not Applicable  Not Applicable
19  ACTIVE  Not Applicable  Not Applicable

In [ ]:
### Data Leakage

#termreason_desc and termtype_desc contain information that becomes known only after an employee leaves the company.

#These columns will be removed before model training.

In [ ]:
x.groupby('EmployeeID').size().describe()

count    6284.000000
mean        7.901496
std         2.861157
min         1.000000
25%         6.000000
50%        10.000000
75%        10.000000
max        10.000000
dtype: float64

In [ ]:
x = x.drop(
    columns=[
        "termreason_desc",
        "termtype_desc"
    ]
)

In [ ]:
x[['gender_short','gender_full']].drop_duplicates()

   gender_short gender_full
0             M        Male
10            F      Female

In [ ]:
x = x.drop(columns=['gender_short'])

In [ ]:
x['STATUS'] = x['STATUS'].map({
    'ACTIVE': 0,
    'TERMINATED': 1
})

In [ ]:
x['STATUS'].value_counts()

STATUS
0    48168
1     1485
Name: count, dtype: int64

In [ ]:
date_cols = [
    'recorddate_key',
    'birthdate_key',
    'orighiredate_key',
    'terminationdate_key'
]

for col in date_cols:
    print(col)
    print(x[col].head())
    print()

recorddate_key
0    12/31/2006 0:00
1    12/31/2007 0:00
2    12/31/2008 0:00
3    12/31/2009 0:00
4    12/31/2010 0:00
Name: recorddate_key, dtype: object

birthdate_key
0    1/3/1954
1    1/3/1954
2    1/3/1954
3    1/3/1954
4    1/3/1954
Name: birthdate_key, dtype: object

orighiredate_key
0    8/28/1989
1    8/28/1989
2    8/28/1989
3    8/28/1989
4    8/28/1989
Name: orighiredate_key, dtype: object

terminationdate_key
0    1/1/1900
1    1/1/1900
2    1/1/1900
3    1/1/1900
4    1/1/1900
Name: terminationdate_key, dtype: object

In [ ]:
columns_to_drop = [
    "EmployeeID",
    "birthdate_key",
    "orighiredate_key",
    "terminationdate_key",
    "termreason_desc",
    "termtype_desc",
    "gender_short"
]

In [ ]:
x.to_csv(
    "cleaned_employee_attrition.csv",
    index=False
)

In [19]:
from google.colab import files
files.download('cleaned_employee_attrition.csv')