In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_employee_attrition.csv to cleaned_employee_attrition.csv

In [ ]:
import pandas as pd

df = pd.read_csv("cleaned_employee_attrition.csv")

df.head()

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_full,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,1/3/1954,8/28/1989,1/1/1900,52,17,Vancouver,Executive,CEO,35,Male,2006,0,HEADOFFICE
1,1318,12/31/2007 0:00,1/3/1954,8/28/1989,1/1/1900,53,18,Vancouver,Executive,CEO,35,Male,2007,0,HEADOFFICE
2,1318,12/31/2008 0:00,1/3/1954,8/28/1989,1/1/1900,54,19,Vancouver,Executive,CEO,35,Male,2008,0,HEADOFFICE
3,1318,12/31/2009 0:00,1/3/1954,8/28/1989,1/1/1900,55,20,Vancouver,Executive,CEO,35,Male,2009,0,HEADOFFICE
4,1318,12/31/2010 0:00,1/3/1954,8/28/1989,1/1/1900,56,21,Vancouver,Executive,CEO,35,Male,2010,0,HEADOFFICE

In [ ]:
df["STATUS"].value_counts()

STATUS
0    48168
1     1485
Name: count, dtype: int64

In [ ]:
df = df.drop(columns=[
    "EmployeeID",
    "recorddate_key",
    "birthdate_key"
])

In [ ]:
df_encoded = pd.get_dummies(df, drop_first=True)

In [ ]:
X = df_encoded.drop("STATUS", axis=1)
y = df_encoded["STATUS"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
y_train.value_counts(normalize=True)

STATUS
0    0.970092
1    0.029908
Name: proportion, dtype: float64

In [ ]:
from google.colab import files

files.download("X_train.csv")